export const camposFormulario = [
  {
    id: "nombre",
    etiqueta: "Nombre",
    modelo: "nombre",
    obligatorio: true,
    ancho: 4,
    mensajeError: "El nombre es obligatorio",
    keyfilter: /^[A-Za-z\s]*$/,
  },
  {
    id: "primerApellido",
    etiqueta: "Primer Apellido",
    modelo: "primerApellido",
    obligatorio: true,
    ancho: 4,
    mensajeError: "El primer apellido es obligatorio",
    keyfilter: /^[A-Za-z\s]*$/,
  },
  {
    id: "segundoApellido",
    etiqueta: "Segundo Apellido",
    modelo: "segundoApellido",
    obligatorio: true,
    ancho: 4,
    mensajeError: "El segundo apellido es obligatorio",
    keyfilter: /^[A-Za-z\s]*$/,
  },
  {
    id: "curp",
    etiqueta: "CURP",
    modelo: "curp",
    obligatorio: true,
    ancho: 6,
    mensajeError: "El CURP es obligatorio",
    keyfilter: /^[A-Za-z0-9]*$/,
    maxlength: 18,
  },
  {
    id: "rfc",
    etiqueta: "RFC (con homoclave)",
    modelo: "rfc",
    obligatorio: true,
    ancho: 6,
    mensajeError: "El RFC es obligatorio",
    keyfilter: /^[A-Za-z0-9]*$/,
    maxlength: 13,
  },
  {
    id: "cp",
    etiqueta: "Código Postal",
    modelo: "cp",
    obligatorio: true,
    ancho: 3,
    mensajeError: "El código postal es obligatorio",
    keyfilter: /^[0-9]*$/,
    maxlength: 5,
  },
  {
    id: "calle",
    etiqueta: "Calle",
    modelo: "calle",
    obligatorio: true,
    ancho: 9,
    mensajeError: "La calle es obligatoria",
    keyfilter: /^[A-Za-z0-9\s]*$/,
  },
  {
    id: "numeroExterior",
    etiqueta: "Número Exterior",
    modelo: "numeroExterior",
    obligatorio: true,
    ancho: 4,
    mensajeError: "El número exterior es obligatorio",
    keyfilter: /^[0-9]*$/,
    maxlength: 5,
  },
  {
    id: "numeroInterior",
    etiqueta: "Número Interior",
    modelo: "numeroInterior",
    obligatorio: false,
    ancho: 4,
    mensajeError: "",
    keyfilter: /^[0-9]*$/,
    maxlength: 10,
  },
  {
    id: "estado",
    etiqueta: "Estado",
    modelo: "estado",
    obligatorio: true,
    ancho: 4,
    mensajeError: "El estado es obligatorio",
    keyfilter: /^[A-Za-z\s]*$/,
  },
  {
    id: "municipio",
    etiqueta: "Delegación/Municipio",
    modelo: "municipio",
    obligatorio: true,
    ancho: 6,
    mensajeError: "El municipio es obligatorio",
    keyfilter: /^[A-Za-z\s]*$/,
  },
  {
    id: "colonia",
    etiqueta: "Colonia",
    modelo: "colonia",
    obligatorio: true,
    ancho: 6,
    mensajeError: "La colonia es obligatoria",
    keyfilter: /^[A-Za-z\s]*$/,
  },
];

export const formatSaveUser = (data) => {
  return {
    infoUsuario: {
      nombre: data.nombre,
      primerApellido: data.primerApellido,
      segundoApellido: data.segundoApellido,
      curp: data.curp,
      rfc: data.rfc,
    },
    Domicilio: {
      cp: data.cp,
      calle: data.calle,
      numExt: data.numeroExterior,
      numInt: data.numeroInterior,
      estado: data.estado,
      municipio: data.municipio,
      colonia: data.colonia,
    },
  };
};

export const formatUpdateUser = (user, infoUser) => {
  return {
    id: infoUser.id,
    name: `${user.nombre} ${user.primerApellido} ${user.segundoApellido}`,
    username: user.nombre,
    email: infoUser.email,
    address: {
      street: user.calle,
      suite: user.numExt,
      city: user.estado,
      zipcode: user.cp,
      geo: {
        lat: infoUser.address.geo.lat ? infoUser.address.geo.lat : "",
        lng: infoUser.address.geo.lng ? infoUser.address.geo.lng : "",
      },
    },
    phone: infoUser.phone,
    website: infoUser.website,
    company: {
      name: infoUser.company.name,
      catchPhrase: infoUser.company.catchPhrase,
      bs: infoUser.company.bs,
    },
  };
};
